-- AlterTable
ALTER TABLE "consulta" ADD COLUMN     "creado" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "especialidad" ADD COLUMN     "creado" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "medico" ADD COLUMN     "creado" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "paciente" ADD COLUMN     "creado" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
