
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Historial` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Historial
 * 
 */
export type HistorialModel = runtime.Types.Result.DefaultSelection<Prisma.$HistorialPayload>

export type AggregateHistorial = {
  _count: HistorialCountAggregateOutputType | null
  _avg: HistorialAvgAggregateOutputType | null
  _sum: HistorialSumAggregateOutputType | null
  _min: HistorialMinAggregateOutputType | null
  _max: HistorialMaxAggregateOutputType | null
}

export type HistorialAvgAggregateOutputType = {
  id: number | null
  id_paciente: number | null
}

export type HistorialSumAggregateOutputType = {
  id: number | null
  id_paciente: number | null
}

export type HistorialMinAggregateOutputType = {
  id: number | null
  id_paciente: number | null
  motivo: string | null
  antecedentes: string | null
  triaje: string | null
  diagnostico: string | null
  tratamiento: string | null
  receta: string | null
  registerdate: Date | null
  deleted: boolean | null
}

export type HistorialMaxAggregateOutputType = {
  id: number | null
  id_paciente: number | null
  motivo: string | null
  antecedentes: string | null
  triaje: string | null
  diagnostico: string | null
  tratamiento: string | null
  receta: string | null
  registerdate: Date | null
  deleted: boolean | null
}

export type HistorialCountAggregateOutputType = {
  id: number
  id_paciente: number
  motivo: number
  antecedentes: number
  triaje: number
  diagnostico: number
  tratamiento: number
  receta: number
  registerdate: number
  deleted: number
  _all: number
}


export type HistorialAvgAggregateInputType = {
  id?: true
  id_paciente?: true
}

export type HistorialSumAggregateInputType = {
  id?: true
  id_paciente?: true
}

export type HistorialMinAggregateInputType = {
  id?: true
  id_paciente?: true
  motivo?: true
  antecedentes?: true
  triaje?: true
  diagnostico?: true
  tratamiento?: true
  receta?: true
  registerdate?: true
  deleted?: true
}

export type HistorialMaxAggregateInputType = {
  id?: true
  id_paciente?: true
  motivo?: true
  antecedentes?: true
  triaje?: true
  diagnostico?: true
  tratamiento?: true
  receta?: true
  registerdate?: true
  deleted?: true
}

export type HistorialCountAggregateInputType = {
  id?: true
  id_paciente?: true
  motivo?: true
  antecedentes?: true
  triaje?: true
  diagnostico?: true
  tratamiento?: true
  receta?: true
  registerdate?: true
  deleted?: true
  _all?: true
}

export type HistorialAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Historial to aggregate.
   */
  where?: Prisma.HistorialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Historials to fetch.
   */
  orderBy?: Prisma.HistorialOrderByWithRelationInput | Prisma.HistorialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HistorialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Historials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Historials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Historials
  **/
  _count?: true | HistorialCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HistorialAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HistorialSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HistorialMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HistorialMaxAggregateInputType
}

export type GetHistorialAggregateType<T extends HistorialAggregateArgs> = {
      [P in keyof T & keyof AggregateHistorial]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHistorial[P]>
    : Prisma.GetScalarType<T[P], AggregateHistorial[P]>
}




export type HistorialGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HistorialWhereInput
  orderBy?: Prisma.HistorialOrderByWithAggregationInput | Prisma.HistorialOrderByWithAggregationInput[]
  by: Prisma.HistorialScalarFieldEnum[] | Prisma.HistorialScalarFieldEnum
  having?: Prisma.HistorialScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HistorialCountAggregateInputType | true
  _avg?: HistorialAvgAggregateInputType
  _sum?: HistorialSumAggregateInputType
  _min?: HistorialMinAggregateInputType
  _max?: HistorialMaxAggregateInputType
}

export type HistorialGroupByOutputType = {
  id: number
  id_paciente: number
  motivo: string
  antecedentes: string | null
  triaje: string
  diagnostico: string | null
  tratamiento: string | null
  receta: string | null
  registerdate: Date
  deleted: boolean
  _count: HistorialCountAggregateOutputType | null
  _avg: HistorialAvgAggregateOutputType | null
  _sum: HistorialSumAggregateOutputType | null
  _min: HistorialMinAggregateOutputType | null
  _max: HistorialMaxAggregateOutputType | null
}

export type GetHistorialGroupByPayload<T extends HistorialGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HistorialGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HistorialGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HistorialGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HistorialGroupByOutputType[P]>
      }
    >
  >



export type HistorialWhereInput = {
  AND?: Prisma.HistorialWhereInput | Prisma.HistorialWhereInput[]
  OR?: Prisma.HistorialWhereInput[]
  NOT?: Prisma.HistorialWhereInput | Prisma.HistorialWhereInput[]
  id?: Prisma.IntFilter<"Historial"> | number
  id_paciente?: Prisma.IntFilter<"Historial"> | number
  motivo?: Prisma.StringFilter<"Historial"> | string
  antecedentes?: Prisma.StringNullableFilter<"Historial"> | string | null
  triaje?: Prisma.StringFilter<"Historial"> | string
  diagnostico?: Prisma.StringNullableFilter<"Historial"> | string | null
  tratamiento?: Prisma.StringNullableFilter<"Historial"> | string | null
  receta?: Prisma.StringNullableFilter<"Historial"> | string | null
  registerdate?: Prisma.DateTimeFilter<"Historial"> | Date | string
  deleted?: Prisma.BoolFilter<"Historial"> | boolean
  paciente?: Prisma.XOR<Prisma.PacienteScalarRelationFilter, Prisma.PacienteWhereInput>
}

export type HistorialOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  id_paciente?: Prisma.SortOrder
  motivo?: Prisma.SortOrder
  antecedentes?: Prisma.SortOrderInput | Prisma.SortOrder
  triaje?: Prisma.SortOrder
  diagnostico?: Prisma.SortOrderInput | Prisma.SortOrder
  tratamiento?: Prisma.SortOrderInput | Prisma.SortOrder
  receta?: Prisma.SortOrderInput | Prisma.SortOrder
  registerdate?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  paciente?: Prisma.PacienteOrderByWithRelationInput
}

export type HistorialWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.HistorialWhereInput | Prisma.HistorialWhereInput[]
  OR?: Prisma.HistorialWhereInput[]
  NOT?: Prisma.HistorialWhereInput | Prisma.HistorialWhereInput[]
  id_paciente?: Prisma.IntFilter<"Historial"> | number
  motivo?: Prisma.StringFilter<"Historial"> | string
  antecedentes?: Prisma.StringNullableFilter<"Historial"> | string | null
  triaje?: Prisma.StringFilter<"Historial"> | string
  diagnostico?: Prisma.StringNullableFilter<"Historial"> | string | null
  tratamiento?: Prisma.StringNullableFilter<"Historial"> | string | null
  receta?: Prisma.StringNullableFilter<"Historial"> | string | null
  registerdate?: Prisma.DateTimeFilter<"Historial"> | Date | string
  deleted?: Prisma.BoolFilter<"Historial"> | boolean
  paciente?: Prisma.XOR<Prisma.PacienteScalarRelationFilter, Prisma.PacienteWhereInput>
}, "id">

export type HistorialOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  id_paciente?: Prisma.SortOrder
  motivo?: Prisma.SortOrder
  antecedentes?: Prisma.SortOrderInput | Prisma.SortOrder
  triaje?: Prisma.SortOrder
  diagnostico?: Prisma.SortOrderInput | Prisma.SortOrder
  tratamiento?: Prisma.SortOrderInput | Prisma.SortOrder
  receta?: Prisma.SortOrderInput | Prisma.SortOrder
  registerdate?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  _count?: Prisma.HistorialCountOrderByAggregateInput
  _avg?: Prisma.HistorialAvgOrderByAggregateInput
  _max?: Prisma.HistorialMaxOrderByAggregateInput
  _min?: Prisma.HistorialMinOrderByAggregateInput
  _sum?: Prisma.HistorialSumOrderByAggregateInput
}

export type HistorialScalarWhereWithAggregatesInput = {
  AND?: Prisma.HistorialScalarWhereWithAggregatesInput | Prisma.HistorialScalarWhereWithAggregatesInput[]
  OR?: Prisma.HistorialScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HistorialScalarWhereWithAggregatesInput | Prisma.HistorialScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Historial"> | number
  id_paciente?: Prisma.IntWithAggregatesFilter<"Historial"> | number
  motivo?: Prisma.StringWithAggregatesFilter<"Historial"> | string
  antecedentes?: Prisma.StringNullableWithAggregatesFilter<"Historial"> | string | null
  triaje?: Prisma.StringWithAggregatesFilter<"Historial"> | string
  diagnostico?: Prisma.StringNullableWithAggregatesFilter<"Historial"> | string | null
  tratamiento?: Prisma.StringNullableWithAggregatesFilter<"Historial"> | string | null
  receta?: Prisma.StringNullableWithAggregatesFilter<"Historial"> | string | null
  registerdate?: Prisma.DateTimeWithAggregatesFilter<"Historial"> | Date | string
  deleted?: Prisma.BoolWithAggregatesFilter<"Historial"> | boolean
}

export type HistorialCreateInput = {
  motivo: string
  antecedentes?: string | null
  triaje: string
  diagnostico?: string | null
  tratamiento?: string | null
  receta?: string | null
  registerdate?: Date | string
  deleted?: boolean
  paciente: Prisma.PacienteCreateNestedOneWithoutHistorialesInput
}

export type HistorialUncheckedCreateInput = {
  id?: number
  id_paciente: number
  motivo: string
  antecedentes?: string | null
  triaje: string
  diagnostico?: string | null
  tratamiento?: string | null
  receta?: string | null
  registerdate?: Date | string
  deleted?: boolean
}

export type HistorialUpdateInput = {
  motivo?: Prisma.StringFieldUpdateOperationsInput | string
  antecedentes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triaje?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tratamiento?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registerdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  paciente?: Prisma.PacienteUpdateOneRequiredWithoutHistorialesNestedInput
}

export type HistorialUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  id_paciente?: Prisma.IntFieldUpdateOperationsInput | number
  motivo?: Prisma.StringFieldUpdateOperationsInput | string
  antecedentes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triaje?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tratamiento?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registerdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type HistorialCreateManyInput = {
  id?: number
  id_paciente: number
  motivo: string
  antecedentes?: string | null
  triaje: string
  diagnostico?: string | null
  tratamiento?: string | null
  receta?: string | null
  registerdate?: Date | string
  deleted?: boolean
}

export type HistorialUpdateManyMutationInput = {
  motivo?: Prisma.StringFieldUpdateOperationsInput | string
  antecedentes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triaje?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tratamiento?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registerdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type HistorialUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  id_paciente?: Prisma.IntFieldUpdateOperationsInput | number
  motivo?: Prisma.StringFieldUpdateOperationsInput | string
  antecedentes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triaje?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tratamiento?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registerdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type HistorialListRelationFilter = {
  every?: Prisma.HistorialWhereInput
  some?: Prisma.HistorialWhereInput
  none?: Prisma.HistorialWhereInput
}

export type HistorialOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type HistorialCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  id_paciente?: Prisma.SortOrder
  motivo?: Prisma.SortOrder
  antecedentes?: Prisma.SortOrder
  triaje?: Prisma.SortOrder
  diagnostico?: Prisma.SortOrder
  tratamiento?: Prisma.SortOrder
  receta?: Prisma.SortOrder
  registerdate?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type HistorialAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  id_paciente?: Prisma.SortOrder
}

export type HistorialMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  id_paciente?: Prisma.SortOrder
  motivo?: Prisma.SortOrder
  antecedentes?: Prisma.SortOrder
  triaje?: Prisma.SortOrder
  diagnostico?: Prisma.SortOrder
  tratamiento?: Prisma.SortOrder
  receta?: Prisma.SortOrder
  registerdate?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type HistorialMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  id_paciente?: Prisma.SortOrder
  motivo?: Prisma.SortOrder
  antecedentes?: Prisma.SortOrder
  triaje?: Prisma.SortOrder
  diagnostico?: Prisma.SortOrder
  tratamiento?: Prisma.SortOrder
  receta?: Prisma.SortOrder
  registerdate?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type HistorialSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  id_paciente?: Prisma.SortOrder
}

export type HistorialCreateNestedManyWithoutPacienteInput = {
  create?: Prisma.XOR<Prisma.HistorialCreateWithoutPacienteInput, Prisma.HistorialUncheckedCreateWithoutPacienteInput> | Prisma.HistorialCreateWithoutPacienteInput[] | Prisma.HistorialUncheckedCreateWithoutPacienteInput[]
  connectOrCreate?: Prisma.HistorialCreateOrConnectWithoutPacienteInput | Prisma.HistorialCreateOrConnectWithoutPacienteInput[]
  createMany?: Prisma.HistorialCreateManyPacienteInputEnvelope
  connect?: Prisma.HistorialWhereUniqueInput | Prisma.HistorialWhereUniqueInput[]
}

export type HistorialUncheckedCreateNestedManyWithoutPacienteInput = {
  create?: Prisma.XOR<Prisma.HistorialCreateWithoutPacienteInput, Prisma.HistorialUncheckedCreateWithoutPacienteInput> | Prisma.HistorialCreateWithoutPacienteInput[] | Prisma.HistorialUncheckedCreateWithoutPacienteInput[]
  connectOrCreate?: Prisma.HistorialCreateOrConnectWithoutPacienteInput | Prisma.HistorialCreateOrConnectWithoutPacienteInput[]
  createMany?: Prisma.HistorialCreateManyPacienteInputEnvelope
  connect?: Prisma.HistorialWhereUniqueInput | Prisma.HistorialWhereUniqueInput[]
}

export type HistorialUpdateManyWithoutPacienteNestedInput = {
  create?: Prisma.XOR<Prisma.HistorialCreateWithoutPacienteInput, Prisma.HistorialUncheckedCreateWithoutPacienteInput> | Prisma.HistorialCreateWithoutPacienteInput[] | Prisma.HistorialUncheckedCreateWithoutPacienteInput[]
  connectOrCreate?: Prisma.HistorialCreateOrConnectWithoutPacienteInput | Prisma.HistorialCreateOrConnectWithoutPacienteInput[]
  upsert?: Prisma.HistorialUpsertWithWhereUniqueWithoutPacienteInput | Prisma.HistorialUpsertWithWhereUniqueWithoutPacienteInput[]
  createMany?: Prisma.HistorialCreateManyPacienteInputEnvelope
  set?: Prisma.HistorialWhereUniqueInput | Prisma.HistorialWhereUniqueInput[]
  disconnect?: Prisma.HistorialWhereUniqueInput | Prisma.HistorialWhereUniqueInput[]
  delete?: Prisma.HistorialWhereUniqueInput | Prisma.HistorialWhereUniqueInput[]
  connect?: Prisma.HistorialWhereUniqueInput | Prisma.HistorialWhereUniqueInput[]
  update?: Prisma.HistorialUpdateWithWhereUniqueWithoutPacienteInput | Prisma.HistorialUpdateWithWhereUniqueWithoutPacienteInput[]
  updateMany?: Prisma.HistorialUpdateManyWithWhereWithoutPacienteInput | Prisma.HistorialUpdateManyWithWhereWithoutPacienteInput[]
  deleteMany?: Prisma.HistorialScalarWhereInput | Prisma.HistorialScalarWhereInput[]
}

export type HistorialUncheckedUpdateManyWithoutPacienteNestedInput = {
  create?: Prisma.XOR<Prisma.HistorialCreateWithoutPacienteInput, Prisma.HistorialUncheckedCreateWithoutPacienteInput> | Prisma.HistorialCreateWithoutPacienteInput[] | Prisma.HistorialUncheckedCreateWithoutPacienteInput[]
  connectOrCreate?: Prisma.HistorialCreateOrConnectWithoutPacienteInput | Prisma.HistorialCreateOrConnectWithoutPacienteInput[]
  upsert?: Prisma.HistorialUpsertWithWhereUniqueWithoutPacienteInput | Prisma.HistorialUpsertWithWhereUniqueWithoutPacienteInput[]
  createMany?: Prisma.HistorialCreateManyPacienteInputEnvelope
  set?: Prisma.HistorialWhereUniqueInput | Prisma.HistorialWhereUniqueInput[]
  disconnect?: Prisma.HistorialWhereUniqueInput | Prisma.HistorialWhereUniqueInput[]
  delete?: Prisma.HistorialWhereUniqueInput | Prisma.HistorialWhereUniqueInput[]
  connect?: Prisma.HistorialWhereUniqueInput | Prisma.HistorialWhereUniqueInput[]
  update?: Prisma.HistorialUpdateWithWhereUniqueWithoutPacienteInput | Prisma.HistorialUpdateWithWhereUniqueWithoutPacienteInput[]
  updateMany?: Prisma.HistorialUpdateManyWithWhereWithoutPacienteInput | Prisma.HistorialUpdateManyWithWhereWithoutPacienteInput[]
  deleteMany?: Prisma.HistorialScalarWhereInput | Prisma.HistorialScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type HistorialCreateWithoutPacienteInput = {
  motivo: string
  antecedentes?: string | null
  triaje: string
  diagnostico?: string | null
  tratamiento?: string | null
  receta?: string | null
  registerdate?: Date | string
  deleted?: boolean
}

export type HistorialUncheckedCreateWithoutPacienteInput = {
  id?: number
  motivo: string
  antecedentes?: string | null
  triaje: string
  diagnostico?: string | null
  tratamiento?: string | null
  receta?: string | null
  registerdate?: Date | string
  deleted?: boolean
}

export type HistorialCreateOrConnectWithoutPacienteInput = {
  where: Prisma.HistorialWhereUniqueInput
  create: Prisma.XOR<Prisma.HistorialCreateWithoutPacienteInput, Prisma.HistorialUncheckedCreateWithoutPacienteInput>
}

export type HistorialCreateManyPacienteInputEnvelope = {
  data: Prisma.HistorialCreateManyPacienteInput | Prisma.HistorialCreateManyPacienteInput[]
  skipDuplicates?: boolean
}

export type HistorialUpsertWithWhereUniqueWithoutPacienteInput = {
  where: Prisma.HistorialWhereUniqueInput
  update: Prisma.XOR<Prisma.HistorialUpdateWithoutPacienteInput, Prisma.HistorialUncheckedUpdateWithoutPacienteInput>
  create: Prisma.XOR<Prisma.HistorialCreateWithoutPacienteInput, Prisma.HistorialUncheckedCreateWithoutPacienteInput>
}

export type HistorialUpdateWithWhereUniqueWithoutPacienteInput = {
  where: Prisma.HistorialWhereUniqueInput
  data: Prisma.XOR<Prisma.HistorialUpdateWithoutPacienteInput, Prisma.HistorialUncheckedUpdateWithoutPacienteInput>
}

export type HistorialUpdateManyWithWhereWithoutPacienteInput = {
  where: Prisma.HistorialScalarWhereInput
  data: Prisma.XOR<Prisma.HistorialUpdateManyMutationInput, Prisma.HistorialUncheckedUpdateManyWithoutPacienteInput>
}

export type HistorialScalarWhereInput = {
  AND?: Prisma.HistorialScalarWhereInput | Prisma.HistorialScalarWhereInput[]
  OR?: Prisma.HistorialScalarWhereInput[]
  NOT?: Prisma.HistorialScalarWhereInput | Prisma.HistorialScalarWhereInput[]
  id?: Prisma.IntFilter<"Historial"> | number
  id_paciente?: Prisma.IntFilter<"Historial"> | number
  motivo?: Prisma.StringFilter<"Historial"> | string
  antecedentes?: Prisma.StringNullableFilter<"Historial"> | string | null
  triaje?: Prisma.StringFilter<"Historial"> | string
  diagnostico?: Prisma.StringNullableFilter<"Historial"> | string | null
  tratamiento?: Prisma.StringNullableFilter<"Historial"> | string | null
  receta?: Prisma.StringNullableFilter<"Historial"> | string | null
  registerdate?: Prisma.DateTimeFilter<"Historial"> | Date | string
  deleted?: Prisma.BoolFilter<"Historial"> | boolean
}

export type HistorialCreateManyPacienteInput = {
  id?: number
  motivo: string
  antecedentes?: string | null
  triaje: string
  diagnostico?: string | null
  tratamiento?: string | null
  receta?: string | null
  registerdate?: Date | string
  deleted?: boolean
}

export type HistorialUpdateWithoutPacienteInput = {
  motivo?: Prisma.StringFieldUpdateOperationsInput | string
  antecedentes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triaje?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tratamiento?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registerdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type HistorialUncheckedUpdateWithoutPacienteInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  motivo?: Prisma.StringFieldUpdateOperationsInput | string
  antecedentes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triaje?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tratamiento?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registerdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type HistorialUncheckedUpdateManyWithoutPacienteInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  motivo?: Prisma.StringFieldUpdateOperationsInput | string
  antecedentes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triaje?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tratamiento?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  receta?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registerdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type HistorialSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  id_paciente?: boolean
  motivo?: boolean
  antecedentes?: boolean
  triaje?: boolean
  diagnostico?: boolean
  tratamiento?: boolean
  receta?: boolean
  registerdate?: boolean
  deleted?: boolean
  paciente?: boolean | Prisma.PacienteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["historial"]>

export type HistorialSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  id_paciente?: boolean
  motivo?: boolean
  antecedentes?: boolean
  triaje?: boolean
  diagnostico?: boolean
  tratamiento?: boolean
  receta?: boolean
  registerdate?: boolean
  deleted?: boolean
  paciente?: boolean | Prisma.PacienteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["historial"]>

export type HistorialSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  id_paciente?: boolean
  motivo?: boolean
  antecedentes?: boolean
  triaje?: boolean
  diagnostico?: boolean
  tratamiento?: boolean
  receta?: boolean
  registerdate?: boolean
  deleted?: boolean
  paciente?: boolean | Prisma.PacienteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["historial"]>

export type HistorialSelectScalar = {
  id?: boolean
  id_paciente?: boolean
  motivo?: boolean
  antecedentes?: boolean
  triaje?: boolean
  diagnostico?: boolean
  tratamiento?: boolean
  receta?: boolean
  registerdate?: boolean
  deleted?: boolean
}

export type HistorialOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "id_paciente" | "motivo" | "antecedentes" | "triaje" | "diagnostico" | "tratamiento" | "receta" | "registerdate" | "deleted", ExtArgs["result"]["historial"]>
export type HistorialInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paciente?: boolean | Prisma.PacienteDefaultArgs<ExtArgs>
}
export type HistorialIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paciente?: boolean | Prisma.PacienteDefaultArgs<ExtArgs>
}
export type HistorialIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paciente?: boolean | Prisma.PacienteDefaultArgs<ExtArgs>
}

export type $HistorialPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Historial"
  objects: {
    paciente: Prisma.$PacientePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    id_paciente: number
    motivo: string
    antecedentes: string | null
    triaje: string
    diagnostico: string | null
    tratamiento: string | null
    receta: string | null
    registerdate: Date
    deleted: boolean
  }, ExtArgs["result"]["historial"]>
  composites: {}
}

export type HistorialGetPayload<S extends boolean | null | undefined | HistorialDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HistorialPayload, S>

export type HistorialCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HistorialFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HistorialCountAggregateInputType | true
  }

export interface HistorialDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Historial'], meta: { name: 'Historial' } }
  /**
   * Find zero or one Historial that matches the filter.
   * @param {HistorialFindUniqueArgs} args - Arguments to find a Historial
   * @example
   * // Get one Historial
   * const historial = await prisma.historial.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HistorialFindUniqueArgs>(args: Prisma.SelectSubset<T, HistorialFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HistorialClient<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Historial that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HistorialFindUniqueOrThrowArgs} args - Arguments to find a Historial
   * @example
   * // Get one Historial
   * const historial = await prisma.historial.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HistorialFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HistorialFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HistorialClient<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Historial that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialFindFirstArgs} args - Arguments to find a Historial
   * @example
   * // Get one Historial
   * const historial = await prisma.historial.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HistorialFindFirstArgs>(args?: Prisma.SelectSubset<T, HistorialFindFirstArgs<ExtArgs>>): Prisma.Prisma__HistorialClient<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Historial that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialFindFirstOrThrowArgs} args - Arguments to find a Historial
   * @example
   * // Get one Historial
   * const historial = await prisma.historial.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HistorialFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HistorialFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HistorialClient<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Historials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Historials
   * const historials = await prisma.historial.findMany()
   * 
   * // Get first 10 Historials
   * const historials = await prisma.historial.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const historialWithIdOnly = await prisma.historial.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HistorialFindManyArgs>(args?: Prisma.SelectSubset<T, HistorialFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Historial.
   * @param {HistorialCreateArgs} args - Arguments to create a Historial.
   * @example
   * // Create one Historial
   * const Historial = await prisma.historial.create({
   *   data: {
   *     // ... data to create a Historial
   *   }
   * })
   * 
   */
  create<T extends HistorialCreateArgs>(args: Prisma.SelectSubset<T, HistorialCreateArgs<ExtArgs>>): Prisma.Prisma__HistorialClient<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Historials.
   * @param {HistorialCreateManyArgs} args - Arguments to create many Historials.
   * @example
   * // Create many Historials
   * const historial = await prisma.historial.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HistorialCreateManyArgs>(args?: Prisma.SelectSubset<T, HistorialCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Historials and returns the data saved in the database.
   * @param {HistorialCreateManyAndReturnArgs} args - Arguments to create many Historials.
   * @example
   * // Create many Historials
   * const historial = await prisma.historial.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Historials and only return the `id`
   * const historialWithIdOnly = await prisma.historial.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HistorialCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HistorialCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Historial.
   * @param {HistorialDeleteArgs} args - Arguments to delete one Historial.
   * @example
   * // Delete one Historial
   * const Historial = await prisma.historial.delete({
   *   where: {
   *     // ... filter to delete one Historial
   *   }
   * })
   * 
   */
  delete<T extends HistorialDeleteArgs>(args: Prisma.SelectSubset<T, HistorialDeleteArgs<ExtArgs>>): Prisma.Prisma__HistorialClient<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Historial.
   * @param {HistorialUpdateArgs} args - Arguments to update one Historial.
   * @example
   * // Update one Historial
   * const historial = await prisma.historial.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HistorialUpdateArgs>(args: Prisma.SelectSubset<T, HistorialUpdateArgs<ExtArgs>>): Prisma.Prisma__HistorialClient<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Historials.
   * @param {HistorialDeleteManyArgs} args - Arguments to filter Historials to delete.
   * @example
   * // Delete a few Historials
   * const { count } = await prisma.historial.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HistorialDeleteManyArgs>(args?: Prisma.SelectSubset<T, HistorialDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Historials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Historials
   * const historial = await prisma.historial.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HistorialUpdateManyArgs>(args: Prisma.SelectSubset<T, HistorialUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Historials and returns the data updated in the database.
   * @param {HistorialUpdateManyAndReturnArgs} args - Arguments to update many Historials.
   * @example
   * // Update many Historials
   * const historial = await prisma.historial.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Historials and only return the `id`
   * const historialWithIdOnly = await prisma.historial.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HistorialUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HistorialUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Historial.
   * @param {HistorialUpsertArgs} args - Arguments to update or create a Historial.
   * @example
   * // Update or create a Historial
   * const historial = await prisma.historial.upsert({
   *   create: {
   *     // ... data to create a Historial
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Historial we want to update
   *   }
   * })
   */
  upsert<T extends HistorialUpsertArgs>(args: Prisma.SelectSubset<T, HistorialUpsertArgs<ExtArgs>>): Prisma.Prisma__HistorialClient<runtime.Types.Result.GetResult<Prisma.$HistorialPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Historials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialCountArgs} args - Arguments to filter Historials to count.
   * @example
   * // Count the number of Historials
   * const count = await prisma.historial.count({
   *   where: {
   *     // ... the filter for the Historials we want to count
   *   }
   * })
  **/
  count<T extends HistorialCountArgs>(
    args?: Prisma.Subset<T, HistorialCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HistorialCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Historial.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HistorialAggregateArgs>(args: Prisma.Subset<T, HistorialAggregateArgs>): Prisma.PrismaPromise<GetHistorialAggregateType<T>>

  /**
   * Group by Historial.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HistorialGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HistorialGroupByArgs['orderBy'] }
      : { orderBy?: HistorialGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HistorialGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHistorialGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Historial model
 */
readonly fields: HistorialFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Historial.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HistorialClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  paciente<T extends Prisma.PacienteDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PacienteDefaultArgs<ExtArgs>>): Prisma.Prisma__PacienteClient<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Historial model
 */
export interface HistorialFieldRefs {
  readonly id: Prisma.FieldRef<"Historial", 'Int'>
  readonly id_paciente: Prisma.FieldRef<"Historial", 'Int'>
  readonly motivo: Prisma.FieldRef<"Historial", 'String'>
  readonly antecedentes: Prisma.FieldRef<"Historial", 'String'>
  readonly triaje: Prisma.FieldRef<"Historial", 'String'>
  readonly diagnostico: Prisma.FieldRef<"Historial", 'String'>
  readonly tratamiento: Prisma.FieldRef<"Historial", 'String'>
  readonly receta: Prisma.FieldRef<"Historial", 'String'>
  readonly registerdate: Prisma.FieldRef<"Historial", 'DateTime'>
  readonly deleted: Prisma.FieldRef<"Historial", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Historial findUnique
 */
export type HistorialFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialInclude<ExtArgs> | null
  /**
   * Filter, which Historial to fetch.
   */
  where: Prisma.HistorialWhereUniqueInput
}

/**
 * Historial findUniqueOrThrow
 */
export type HistorialFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialInclude<ExtArgs> | null
  /**
   * Filter, which Historial to fetch.
   */
  where: Prisma.HistorialWhereUniqueInput
}

/**
 * Historial findFirst
 */
export type HistorialFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialInclude<ExtArgs> | null
  /**
   * Filter, which Historial to fetch.
   */
  where?: Prisma.HistorialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Historials to fetch.
   */
  orderBy?: Prisma.HistorialOrderByWithRelationInput | Prisma.HistorialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Historials.
   */
  cursor?: Prisma.HistorialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Historials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Historials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Historials.
   */
  distinct?: Prisma.HistorialScalarFieldEnum | Prisma.HistorialScalarFieldEnum[]
}

/**
 * Historial findFirstOrThrow
 */
export type HistorialFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialInclude<ExtArgs> | null
  /**
   * Filter, which Historial to fetch.
   */
  where?: Prisma.HistorialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Historials to fetch.
   */
  orderBy?: Prisma.HistorialOrderByWithRelationInput | Prisma.HistorialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Historials.
   */
  cursor?: Prisma.HistorialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Historials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Historials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Historials.
   */
  distinct?: Prisma.HistorialScalarFieldEnum | Prisma.HistorialScalarFieldEnum[]
}

/**
 * Historial findMany
 */
export type HistorialFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialInclude<ExtArgs> | null
  /**
   * Filter, which Historials to fetch.
   */
  where?: Prisma.HistorialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Historials to fetch.
   */
  orderBy?: Prisma.HistorialOrderByWithRelationInput | Prisma.HistorialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Historials.
   */
  cursor?: Prisma.HistorialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Historials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Historials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Historials.
   */
  distinct?: Prisma.HistorialScalarFieldEnum | Prisma.HistorialScalarFieldEnum[]
}

/**
 * Historial create
 */
export type HistorialCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialInclude<ExtArgs> | null
  /**
   * The data needed to create a Historial.
   */
  data: Prisma.XOR<Prisma.HistorialCreateInput, Prisma.HistorialUncheckedCreateInput>
}

/**
 * Historial createMany
 */
export type HistorialCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Historials.
   */
  data: Prisma.HistorialCreateManyInput | Prisma.HistorialCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Historial createManyAndReturn
 */
export type HistorialCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * The data used to create many Historials.
   */
  data: Prisma.HistorialCreateManyInput | Prisma.HistorialCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Historial update
 */
export type HistorialUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialInclude<ExtArgs> | null
  /**
   * The data needed to update a Historial.
   */
  data: Prisma.XOR<Prisma.HistorialUpdateInput, Prisma.HistorialUncheckedUpdateInput>
  /**
   * Choose, which Historial to update.
   */
  where: Prisma.HistorialWhereUniqueInput
}

/**
 * Historial updateMany
 */
export type HistorialUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Historials.
   */
  data: Prisma.XOR<Prisma.HistorialUpdateManyMutationInput, Prisma.HistorialUncheckedUpdateManyInput>
  /**
   * Filter which Historials to update
   */
  where?: Prisma.HistorialWhereInput
  /**
   * Limit how many Historials to update.
   */
  limit?: number
}

/**
 * Historial updateManyAndReturn
 */
export type HistorialUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * The data used to update Historials.
   */
  data: Prisma.XOR<Prisma.HistorialUpdateManyMutationInput, Prisma.HistorialUncheckedUpdateManyInput>
  /**
   * Filter which Historials to update
   */
  where?: Prisma.HistorialWhereInput
  /**
   * Limit how many Historials to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Historial upsert
 */
export type HistorialUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialInclude<ExtArgs> | null
  /**
   * The filter to search for the Historial to update in case it exists.
   */
  where: Prisma.HistorialWhereUniqueInput
  /**
   * In case the Historial found by the `where` argument doesn't exist, create a new Historial with this data.
   */
  create: Prisma.XOR<Prisma.HistorialCreateInput, Prisma.HistorialUncheckedCreateInput>
  /**
   * In case the Historial was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HistorialUpdateInput, Prisma.HistorialUncheckedUpdateInput>
}

/**
 * Historial delete
 */
export type HistorialDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialInclude<ExtArgs> | null
  /**
   * Filter which Historial to delete.
   */
  where: Prisma.HistorialWhereUniqueInput
}

/**
 * Historial deleteMany
 */
export type HistorialDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Historials to delete
   */
  where?: Prisma.HistorialWhereInput
  /**
   * Limit how many Historials to delete.
   */
  limit?: number
}

/**
 * Historial without action
 */
export type HistorialDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Historial
   */
  select?: Prisma.HistorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Historial
   */
  omit?: Prisma.HistorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistorialInclude<ExtArgs> | null
}
