import type { Prisma } from '../../generated-client/browser';
import * as z from 'zod';
import { UsuarioWhereInputObjectSchema as UsuarioWhereInputObjectSchema } from './objects/UsuarioWhereInput.schema';
import { UsuarioOrderByWithAggregationInputObjectSchema as UsuarioOrderByWithAggregationInputObjectSchema } from './objects/UsuarioOrderByWithAggregationInput.schema';
import { UsuarioScalarWhereWithAggregatesInputObjectSchema as UsuarioScalarWhereWithAggregatesInputObjectSchema } from './objects/UsuarioScalarWhereWithAggregatesInput.schema';
import { UsuarioScalarFieldEnumSchema } from './enums/UsuarioScalarFieldEnum.schema';
import { UsuarioCountAggregateInputObjectSchema as UsuarioCountAggregateInputObjectSchema } from './objects/UsuarioCountAggregateInput.schema';
import { UsuarioMinAggregateInputObjectSchema as UsuarioMinAggregateInputObjectSchema } from './objects/UsuarioMinAggregateInput.schema';
import { UsuarioMaxAggregateInputObjectSchema as UsuarioMaxAggregateInputObjectSchema } from './objects/UsuarioMaxAggregateInput.schema';
import { UsuarioAvgAggregateInputObjectSchema as UsuarioAvgAggregateInputObjectSchema } from './objects/UsuarioAvgAggregateInput.schema';
import { UsuarioSumAggregateInputObjectSchema as UsuarioSumAggregateInputObjectSchema } from './objects/UsuarioSumAggregateInput.schema';

export const UsuarioGroupBySchema: z.ZodType<Prisma.UsuarioGroupByArgs> = z.object({ where: UsuarioWhereInputObjectSchema.optional(), orderBy: z.union([UsuarioOrderByWithAggregationInputObjectSchema, UsuarioOrderByWithAggregationInputObjectSchema.array()]).optional(), having: UsuarioScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(UsuarioScalarFieldEnumSchema), _count: z.union([ z.literal(true), UsuarioCountAggregateInputObjectSchema ]).optional(), _min: UsuarioMinAggregateInputObjectSchema.optional(), _max: UsuarioMaxAggregateInputObjectSchema.optional(), _avg: UsuarioAvgAggregateInputObjectSchema.optional(), _sum: UsuarioSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.UsuarioGroupByArgs>;

export const UsuarioGroupByZodSchema = z.object({ where: UsuarioWhereInputObjectSchema.optional(), orderBy: z.union([UsuarioOrderByWithAggregationInputObjectSchema, UsuarioOrderByWithAggregationInputObjectSchema.array()]).optional(), having: UsuarioScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(UsuarioScalarFieldEnumSchema), _count: z.union([ z.literal(true), UsuarioCountAggregateInputObjectSchema ]).optional(), _min: UsuarioMinAggregateInputObjectSchema.optional(), _max: UsuarioMaxAggregateInputObjectSchema.optional(), _avg: UsuarioAvgAggregateInputObjectSchema.optional(), _sum: UsuarioSumAggregateInputObjectSchema.optional() }).strict();