import type { Prisma } from '../../generated-client/browser';
import * as z from 'zod';
import { MedicoWhereInputObjectSchema as MedicoWhereInputObjectSchema } from './objects/MedicoWhereInput.schema';
import { MedicoOrderByWithAggregationInputObjectSchema as MedicoOrderByWithAggregationInputObjectSchema } from './objects/MedicoOrderByWithAggregationInput.schema';
import { MedicoScalarWhereWithAggregatesInputObjectSchema as MedicoScalarWhereWithAggregatesInputObjectSchema } from './objects/MedicoScalarWhereWithAggregatesInput.schema';
import { MedicoScalarFieldEnumSchema } from './enums/MedicoScalarFieldEnum.schema';
import { MedicoCountAggregateInputObjectSchema as MedicoCountAggregateInputObjectSchema } from './objects/MedicoCountAggregateInput.schema';
import { MedicoMinAggregateInputObjectSchema as MedicoMinAggregateInputObjectSchema } from './objects/MedicoMinAggregateInput.schema';
import { MedicoMaxAggregateInputObjectSchema as MedicoMaxAggregateInputObjectSchema } from './objects/MedicoMaxAggregateInput.schema';
import { MedicoAvgAggregateInputObjectSchema as MedicoAvgAggregateInputObjectSchema } from './objects/MedicoAvgAggregateInput.schema';
import { MedicoSumAggregateInputObjectSchema as MedicoSumAggregateInputObjectSchema } from './objects/MedicoSumAggregateInput.schema';

export const MedicoGroupBySchema: z.ZodType<Prisma.MedicoGroupByArgs> = z.object({ where: MedicoWhereInputObjectSchema.optional(), orderBy: z.union([MedicoOrderByWithAggregationInputObjectSchema, MedicoOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MedicoScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MedicoScalarFieldEnumSchema), _count: z.union([ z.literal(true), MedicoCountAggregateInputObjectSchema ]).optional(), _min: MedicoMinAggregateInputObjectSchema.optional(), _max: MedicoMaxAggregateInputObjectSchema.optional(), _avg: MedicoAvgAggregateInputObjectSchema.optional(), _sum: MedicoSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MedicoGroupByArgs>;

export const MedicoGroupByZodSchema = z.object({ where: MedicoWhereInputObjectSchema.optional(), orderBy: z.union([MedicoOrderByWithAggregationInputObjectSchema, MedicoOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MedicoScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MedicoScalarFieldEnumSchema), _count: z.union([ z.literal(true), MedicoCountAggregateInputObjectSchema ]).optional(), _min: MedicoMinAggregateInputObjectSchema.optional(), _max: MedicoMaxAggregateInputObjectSchema.optional(), _avg: MedicoAvgAggregateInputObjectSchema.optional(), _sum: MedicoSumAggregateInputObjectSchema.optional() }).strict();