import type { Prisma } from '../../generated-client/browser';
import * as z from 'zod';
import { ConsultaWhereInputObjectSchema as ConsultaWhereInputObjectSchema } from './objects/ConsultaWhereInput.schema';
import { ConsultaOrderByWithAggregationInputObjectSchema as ConsultaOrderByWithAggregationInputObjectSchema } from './objects/ConsultaOrderByWithAggregationInput.schema';
import { ConsultaScalarWhereWithAggregatesInputObjectSchema as ConsultaScalarWhereWithAggregatesInputObjectSchema } from './objects/ConsultaScalarWhereWithAggregatesInput.schema';
import { ConsultaScalarFieldEnumSchema } from './enums/ConsultaScalarFieldEnum.schema';
import { ConsultaCountAggregateInputObjectSchema as ConsultaCountAggregateInputObjectSchema } from './objects/ConsultaCountAggregateInput.schema';
import { ConsultaMinAggregateInputObjectSchema as ConsultaMinAggregateInputObjectSchema } from './objects/ConsultaMinAggregateInput.schema';
import { ConsultaMaxAggregateInputObjectSchema as ConsultaMaxAggregateInputObjectSchema } from './objects/ConsultaMaxAggregateInput.schema';
import { ConsultaAvgAggregateInputObjectSchema as ConsultaAvgAggregateInputObjectSchema } from './objects/ConsultaAvgAggregateInput.schema';
import { ConsultaSumAggregateInputObjectSchema as ConsultaSumAggregateInputObjectSchema } from './objects/ConsultaSumAggregateInput.schema';

export const ConsultaGroupBySchema: z.ZodType<Prisma.ConsultaGroupByArgs> = z.object({ where: ConsultaWhereInputObjectSchema.optional(), orderBy: z.union([ConsultaOrderByWithAggregationInputObjectSchema, ConsultaOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ConsultaScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ConsultaScalarFieldEnumSchema), _count: z.union([ z.literal(true), ConsultaCountAggregateInputObjectSchema ]).optional(), _min: ConsultaMinAggregateInputObjectSchema.optional(), _max: ConsultaMaxAggregateInputObjectSchema.optional(), _avg: ConsultaAvgAggregateInputObjectSchema.optional(), _sum: ConsultaSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ConsultaGroupByArgs>;

export const ConsultaGroupByZodSchema = z.object({ where: ConsultaWhereInputObjectSchema.optional(), orderBy: z.union([ConsultaOrderByWithAggregationInputObjectSchema, ConsultaOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ConsultaScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ConsultaScalarFieldEnumSchema), _count: z.union([ z.literal(true), ConsultaCountAggregateInputObjectSchema ]).optional(), _min: ConsultaMinAggregateInputObjectSchema.optional(), _max: ConsultaMaxAggregateInputObjectSchema.optional(), _avg: ConsultaAvgAggregateInputObjectSchema.optional(), _sum: ConsultaSumAggregateInputObjectSchema.optional() }).strict();