
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Paciente: 'Paciente',
  Historial: 'Historial',
  Cita: 'Cita',
  Consulta: 'Consulta',
  Medico: 'Medico',
  Especialidad: 'Especialidad',
  User: 'User'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const PacienteScalarFieldEnum = {
  id: 'id',
  nombres: 'nombres',
  apellidos: 'apellidos',
  telefono: 'telefono',
  email: 'email',
  masculino: 'masculino',
  fecha_nac: 'fecha_nac',
  tipoSangre: 'tipoSangre',
  alergias: 'alergias',
  creado: 'creado'
} as const

export type PacienteScalarFieldEnum = (typeof PacienteScalarFieldEnum)[keyof typeof PacienteScalarFieldEnum]


export const HistorialScalarFieldEnum = {
  id: 'id',
  idPaciente: 'idPaciente',
  fecha: 'fecha',
  motivo: 'motivo',
  antecedentes: 'antecedentes',
  triaje: 'triaje',
  diagnostico: 'diagnostico',
  tratamiento: 'tratamiento',
  receta: 'receta'
} as const

export type HistorialScalarFieldEnum = (typeof HistorialScalarFieldEnum)[keyof typeof HistorialScalarFieldEnum]


export const CitaScalarFieldEnum = {
  id: 'id',
  idPaciente: 'idPaciente',
  fecha: 'fecha',
  estado: 'estado',
  pagoInicial: 'pagoInicial'
} as const

export type CitaScalarFieldEnum = (typeof CitaScalarFieldEnum)[keyof typeof CitaScalarFieldEnum]


export const ConsultaScalarFieldEnum = {
  id: 'id',
  idCita: 'idCita',
  idMedico: 'idMedico',
  fecha: 'fecha',
  horario: 'horario',
  costo: 'costo',
  creado: 'creado'
} as const

export type ConsultaScalarFieldEnum = (typeof ConsultaScalarFieldEnum)[keyof typeof ConsultaScalarFieldEnum]


export const MedicoScalarFieldEnum = {
  id: 'id',
  idEspecialidad: 'idEspecialidad',
  nombres: 'nombres',
  apellidos: 'apellidos',
  telefono: 'telefono',
  email: 'email',
  masculino: 'masculino',
  fechaNac: 'fechaNac',
  creado: 'creado'
} as const

export type MedicoScalarFieldEnum = (typeof MedicoScalarFieldEnum)[keyof typeof MedicoScalarFieldEnum]


export const EspecialidadScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  creado: 'creado'
} as const

export type EspecialidadScalarFieldEnum = (typeof EspecialidadScalarFieldEnum)[keyof typeof EspecialidadScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  role: 'role',
  nombres: 'nombres',
  apellidos: 'apellidos',
  activo: 'activo'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

